### ISSUE TITLE
Views storage location

### ISSUE THREAD

**Issue by TheShimmy** [michalk93/arnolday#1]
We started placing views in our bundle's own resources' directory. Though it may be convenient while using multiple bundles, in our project this may cause us some trouble (especially, using prefixes).

I suggest we stuck to best practices (http://symfony.com/doc/current/best_practices/templates.html#template-locations) and reformat our views files. If we agree, I'll be the one to refactor it.

**Comment by daresh** [comment]
I was placing my views in app/Resourcs/views/category. Don't know why they are also in the AppBundle/Resources.

As for me go ahead - refactor them :+1:
